[build]
  command = "npm run build"
  publish = "frontend/build"

[build.environment]
  NODE_VERSION = "18"

# Disable automatic plugin detection
[build.processing]
  skip_processing = false

# Explicitly disable Next.js plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"
  enabled = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
